services:
  flask-app:
    build: .
    container_name: birthday-reminder
    env_file:
      - .env
    environment:
      - TZ=Europe/Minsk
    ports:
      - "5000:5000"
    volumes:
      - sqlite_data:/app/instance
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  sqlite_data:

